# coding=utf-8 
import py2neo 
from py2neo import Graph,Node,Relationship,NodeMatcher
import pandas as pd
from tqdm import tqdm
import csv
graph = Graph("http://localhost:7474", username='neo4j', password='c224510.', run="sub")
graph.delete_all()
df = pd.read_csv('/home/c/zhishitupu/KGnew.csv',encoding='gbk')

with open('/home/c/zhishitupu/KG.csv','r',encoding='gbk') as f:
    reader = csv.reader(f)
    data = list(reader)
print(data[0])

zstp = Node('复杂场景下的驾驶员注视区域认知图谱',name='复杂场景下的驾驶员注视区域认知图谱')
graph.create(zstp)
scence_1 = Node('场景',name='市区')
scence_2 = Node('场景',name='高速公路')
scence_3 = Node('场景',name='乡间小路')
graph.create(scence_1)
graph.create(scence_2)
graph.create(scence_3)
relation_1 = Relationship(zstp,'驾驶环境',scence_1)
relation_2 = Relationship(zstp,'驾驶环境',scence_2)
relation_3 = Relationship(zstp,'驾驶环境',scence_3)
graph.create(relation_1)
graph.create(relation_2)
graph.create(relation_3)

position_1 = Node('位置',name='有红绿灯的路口')
position_2 = Node('位置',name='无红绿灯的路口')
position_3 = Node('位置',name='非路口')
position_4 = Node('位置',name='环路')
graph.create(position_1)
graph.create(position_2)
graph.create(position_3)
graph.create(position_4)
relation_4 = Relationship(scence_1,'所处位置',position_1)
relation_5 = Relationship(scence_1,'所处位置',position_2)
relation_6 = Relationship(scence_1,'所处位置',position_3)
relation_7 = Relationship(scence_1,'所处位置',position_4)
graph.create(relation_4)
graph.create(relation_5)
graph.create(relation_6)
graph.create(relation_7)
behavier_1 = Node('驾驶行为',name='左转')
behavier_2 = Node('驾驶行为',name='直行')
behavier_3 = Node('驾驶行为',name='右转')
graph.create(behavier_1)
graph.create(behavier_2)
graph.create(behavier_3)
relation_7 = Relationship(position_1,'所处位置',behavier_1)
relation_8 = Relationship(position_1,'所处位置',behavier_2)
relation_9 = Relationship(position_1,'所处位置',behavier_3)
graph.create(relation_7)
graph.create(relation_8)
graph.create(relation_9)

class_1 = Node('类别',name='汽车')
class_2 = Node('类别',name='红绿灯')
class_3 = Node('类别',name='行人')
class_4 = Node('类别',name='骑行者')
class_5 = Node('类别',name='指示牌')
graph.create(class_1)
graph.create(class_2)
graph.create(class_3)
graph.create(class_4)
graph.create(class_5)
relation_10 = Relationship(behavier_1,'关注类别',class_1)
relation_11 = Relationship(behavier_1,'动作',class_2)
relation_12 = Relationship(behavier_1,'动作',class_3)
relation_13 = Relationship(behavier_1,'动作',class_4)
relation_14 = Relationship(behavier_2,'动作',class_1)
relation_15 = Relationship(behavier_2,'动作',class_2)
relation_16 = Relationship(behavier_2,'动作',class_3)
relation_17 = Relationship(behavier_2,'动作',class_4)
relation_18 = Relationship(behavier_3,'动作',class_1)
relation_19 = Relationship(behavier_3,'动作',class_2)
relation_20 = Relationship(behavier_3,'动作',class_3)
relation_21 = Relationship(behavier_3,'动作',class_4)
graph.create(relation_10)
graph.create(relation_11)
graph.create(relation_12)
graph.create(relation_13)
graph.create(relation_14)
graph.create(relation_15)
graph.create(relation_16)
graph.create(relation_17)
graph.create(relation_18)
graph.create(relation_19)
graph.create(relation_20)
graph.create(relation_21)

